blocks:
  - "SHORT_GRASS"
  - "TALL_GRASS"
  - "FERN"
  - "LARGE_FERN"
  - "DEAD_BUSH"
  - "SWEET_BERRIES"
  - "TORCHFLOWER"
  - "PITCHER_POD"
  - "PITCHER_PLANT"
  - "PINK_PETALS"
  - "WILDFLOWERS"
  - "BAMBOO"
  - "CACTUS"
  - "SUGAR_CANE"
  - "BROWN_MUSHROOM"
  - "RED_MUSHROOM"
  - "CRIMSON_FUNGUS"
  - "WARPED_FUNGUS"
  - "CRIMSON_ROOTS"
  - "WARPED_ROOTS"
  - "NETHER_SPROUTS"
  - "NETHER_WART"
  - "AZALEA"
  - "FLOWERING_AZALEA"
  - "MOSS_CARPET"
  - "HANGING_ROOTS"
  - "SPORE_BLOSSOM"
  - "BIG_DRIPLEAF"
  - "SMALL_DRIPLEAF"
  - "CHORUS_FLOWER"
  - "KELP"
  - "SEAGRASS"
  - "SEA_PICKLE"
  - "TALL_SEAGRASS"
  - "PEONY"
  - "ROSE_BUSH"
  - "LILAC"
  - "SUNFLOWER"
  - "POPPY"
  - "CORNFLOWER"
  - "OAK_SAPLING"
  - "SPRUCE_SAPLING"
  - "BIRCH_SAPLING"
  - "JUNGLE_SAPLING"
  - "ACACIA_SAPLING"
  - "DARK_OAK_SAPLING"
  - "CHERRY_SAPLING"
  - "PALE_OAK_SAPLING"
  - "OAK_BUTTON"
  - "TALL_DRY_GRASS"
  - "LILY_PAD"
  - "TORCH"
  - "SOUL_TORCH"
  - "COPPER_TORCH"
  - "REDSTONE_TORCH"
  - "MANGROVE_PROPAGULE"
  - "FIREFLY_BUSH"
  - "RED_TULIP"
  - "ORANGE_TULIP"
  - "PINK_TULIP"
  - "WHITE_TULIP"
  - "FERN"
  - "BLUE_ORCHID"
  - "ALLIUM"
  - "AZURE_BLUET"
  - "OXEYE_DAISY"
  - "LILY_OF_THE_VALLEY"
  - "CLOSED_EYEBLOSSOM"
  - "OPEN_EYEBLOSSOM"
  - "WITHER_ROSE"
  - "LEAF_LITTER"

disable-physics: true